---
title: "Fragman Reporte"
author: "FragmanUI, `r Sys.time()`"
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook:
    config:
      toc:
        collapse: subsection
        scroll_highlight: yes
        before: null
        after: null
      toolbar:
        position: fixed
      edit : null
      download: null
      search: null
      fontsettings:
        theme: white
        family: sans
        size: 2
      sharing: null
---

# Antecedentes

Este reporte ha sido generado automáticamente.

## Gráfico de los datos crudos

```{r , echo=FALSE, message=FALSE}

folder <- "{{results_dir}}"

scores_bin <- readRDS(file.path(folder, "scores_bin.Rds"))

scorebin <- scores_bin[, -c(1,2)]
#rownames(scorebin) <- scores_bin[, 1]

d3heatmap::d3heatmap(scorebin, colors = c("white", "grey", "black"))

```

## Tabla

```{r , echo=FALSE, message=FALSE}

DT::datatable(scores_bin)

```


## Dendrograma


```{r , echo=FALSE}

dend <- agricolae::consensus(scores_bin)$dendrogram


```


